### ISSUE TITLE
complex networks and text mining analytics

### ISSUE THREAD

**Issue by ttm** [zenodo/zenodo#1040]
It seems to me that an interface for further data analytics would enhance
our experience.
I can tackle this by using complex networks and text mining techniques,
because I have developed research on these topics.
Immediate ideas are:
*) Derive network by users interactions and vocabulary usage and deliver some graphical interfaces for exploring these structures.
*) Counting of words, tags, terms and user activity.
*) Maybe develop these features coupled to Researcher Profiles, as described in the ideas page for GSoC 2017.
*) Community pages can also benefit from the analyzes.

I understand it might be late for coping with GSoC, but if you find it suitable,
I might apply.
My apologies for not making this contact earlier, but I handed my doctorate
dissertation a few days ago and could not concentrate as needed until now.
Some info about my research and software development efforts are gathered here:
https://pastebin.com/iNNuN4fy
Anyway, this topic might be of use for the Zenodo community as a whole and for
developments outside GSoC.

Best Regards!
Renato Fabbri

**Comment by krzysztof** [comment]
Hey Renato, thanks you for the ideas!

Do you have an online or offline analyzer in mind?
Analyzing and then gathering such information would indeed be interesting and great to know for later development. I guess the "cheapest" way to get that would be to do it offline, and skip all of the web development part.

> *) Derive network by users interactions and vocabulary usage and deliver some graphical interfaces for exploring these structures.

At the moment there isn't so much inter-user interactions on Zenodo, since we don't have almost any of the "social" features built in Zenodo. The most interesting data we have is probably in the metadata of records. We have a similar GSoC project on the table related to record metadata analysis, but there is surely some interesting network information to harvest from the records cross-references and relations to the authors. Building a citation graph and authors disambiguation are probably two of the most relevant topics in general for a service like ours.

> I understand it might be late for coping with GSoC, but if you find it suitable, I might apply.

I think it might be too late to consider it as GSoC project - we would need more time to refine a custom idea like this one (especially non-trivial one) into something more concrete. Nonetheless, this topic is very relevant to our community - if that would ever suit your line of research we would be more than happy to assist you in harvesting and helping you interpret the metadata we currently have.

> Some info about my research and software development efforts are gathered here: https://pastebin.com/iNNuN4fy7

Page seems to be empty.

**Comment by ttm** [comment]
Hi Krzysztof,
the link is:
https://pastebin.com/iNNuN4fy
(already corrected in the initial message).

I thought I have seen a way to favorite entries (which would yield interactions).
Anyway, authors interact through co-authorship, using same keywords and vocabulary. Any other criteria comes to mind? Posting to the same community does not seem to me as an interaction criterion which would reveal significant structures, although limiting the scope of some analysis to a community seems nice.

I agree that the less computational intensive way to do this is offline, even if we wish to render online interfaces, it might not be feasible (or wanted) to fetch data every time the URL is accessed.
I have experience in Python (mainly for scientific computing e.g. Numpy, but also for web e.g. Flask) and Javascript (e.g. D3.js) so it might be nice to develop the data mining routines and a web interface integrated to Zenodo which exposes the structures and statistics. Maybe the analysis should be done periodically, once per hour, day or week, what do you think?

I did not find in the documentation a way to access Zenodo data. I apologize if I have not looked through everything, but could you give me directions?

Yes, this fits my research and maybe a GSoC application might help us develop these ideas, even if it is not accepted. Anyway, a Brazilian research funding institution might support a postdoctorate in near future, but they are not doing very well at the moment, so if I might try to find some other subsidy.

Thanks for the cordiality.

**Comment by krzysztof** [comment]
> I thought I have seen a way to favorite entries (which would yield interactions).

At the moment it's not possible to "like" records, although it's in the ideas for the researcher's profiles project. But even then, this would be only useful if we decided to make this data publicly available (I'm not sure about that). The best corpus to work on would be still the Record's public metadata. At the moment I can't think of any other significant user interaction other than: authorship, referencing ("references" metadata but also "related/alternate_identifier") and "communities".

> it might be nice to develop the data mining routines and a web interface integrated to Zenodo which exposes the structures and statistics. Maybe the analysis should be done periodically, once per hour, day or week, what do you think?

My gut feeling is that unless you were to gain confidence that we can mine some relevant information, build the whole infrastructure around it could be an overkill.

> I did not find in the documentation a way to access Zenodo data. I apologize if I have not looked through everything, but could you give me directions?

Record's metadata be obtained through REST API: http://developers.zenodo.org , there is also a snapshot of Zenodo's full metadata: https://zenodo.org/record/375909
At the moment you won't be able to get any information other than the Record's metadata. We don't capture the "user" events in any persistent way, nor do we expose it publicly, so that might be impossible to mine at this moment.

> Yes, this fits my research and maybe a GSoC application might help us develop these ideas, even if it is not accepted. Anyway, a Brazilian research funding institution might support a postdoctorate in near future, but they are not doing very well at the moment, so if I might try to find some other subsidy.

Feel free to write it up as GSoC proposal and submit it - we will give you feedback on it, but I can tell you right now that chances of getting it in are very slim, primarily because:

a) I don't think any of the mentors is familiar with this topic well enough to pick it up, and successfully
mentor you through the project
b) It would be very experimental and "risky" compared to other projects, especially given the little time that's left to refine it into some concrete deliverable. This would be an interesting research project, but I feel it requires more time to define properly.

Those two points are relevant only within the frame of GSoC, since is has very concrete requirements (mentor's attention to the project, concrete deliverable within the GSoC time frame, deadlines with measurable progress etc.). Outside of GSoC framework you'd be free to pursue it as you see fit, and since there would be more time, you could get a better intuition of how such research project could be led to yield some interesting results.
