### ISSUE TITLE
How are filenames normalized?

### ISSUE THREAD

**Issue by targos** [zenodo/zenodo#1042]
Hello, I am writing an application to upload chemical data to Zenodo. Our entries are JSON with file attachments (stored in CouchDB).
While experimenting with the sandox, we saw that filenames are normalized during upload (some characters like slash or space are replaced by an underscore).
I wonder if there is a list of such characters or a RegExp that I could use to replicate this behavior because I'd like to be able to predict the Zenodo name from the one that I have in my JSON object.

**Comment by lnielsen** [comment]
The file names are normalised by this function Werkzeug's [``secure_filename``](https://github.com/pallets/werkzeug/blob/master/werkzeug/utils.py#L253-L295).

You can however use our new Files API which is already deployed and working, but which we haven't officially released yet. This API is used by our JavaScript uploader in the UI, and doesn't do any filename normalisation.

Here’s a cURL example for using the new API:

```console
$ curl -X PUT -H "Accept: application/json" -H "Content-Type: application/octet-stream" -H "Authorization: Bearer <access_token>" -d @<path to local file> https://www.zenodo.org/api/files/<bucket-id>/<filename>
```

Note that the new Files API is versioned, so if you execute an upload twice, it will create a new version of the file, but the old version will still stay around. In order to remove a file you must issue a DELETE request to specific version:

```console
$ curl -X DELETE -H "Accept: application/json" -H "Authorization: Bearer <access_token>" https://www.zenodo.org/api/files/<bucket-id>/<remote filename>?versionId=<uuid>”
```

You get the ``<bucket-id>`` from the your deposit:

```console
$ curl -H "Accept: application/json" -H "Authorization: Bearer <access token>" "https://www.zenodo.org/api/deposit/depositions/<deposit-id>"
```

**Comment by targos** [comment]
Thank you.
