### ISSUE TITLE
author profile section

### ISSUE THREAD

**Issue by MarcoMinghini** [zenodo/zenodo#1207]
It would be great to have an author profile section, i.e. a single place where I can access all the documents having me as an author (those uploaded by me and also those uploaded by others of which I am an author).

**Comment by lnielsen** [comment]
We have a Google Summer of Code project to create Research Profiles - if it works out you should have something pretty close to what you are asking. It will show everything you uploaded, and everything where your ORCID appears (if you linked your ORCID account). It won't be smarter than that, since author disambiguation is pretty difficult and would be very time consuming for us to do now.

**Comment by MarcoMinghini** [comment]
That is great, thank you for the information and the great work to improve Zenodo!

**Comment by jmason888-berkeley** [comment]
This will be nice to see, since currently I my profile doesn't even *show* me my ORCID, let alone use it in a search...

**Comment by slint** [comment]
Closed in favor of https://github.com/zenodo/zenodo/issues/1212
