### ISSUE TITLE
openaire: update publication type mapping 

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1270]

**Comment by lnielsen** [comment]
https://issue.openaire.research-infrastructures.eu/issues/2938

![screen shot 2017-08-22 at 10 41 00](https://user-images.githubusercontent.com/1698163/29556557-7e2aadf4-8726-11e7-911d-4601a8cdf99b.png)

https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/data/objecttypes.json

**Comment by slint** [comment]
Do we update only `code` -> [`openaire.resourceType`](https://github.com/zenodo/zenodo/blob/ef415ddf4d9839515d9e8c0b82d2585703e0812c/zenodo/modules/records/data/objecttypes.json#L48), or also `term openaire` -> [`openaire.type`](https://github.com/zenodo/zenodo/blob/ef415ddf4d9839515d9e8c0b82d2585703e0812c/zenodo/modules/records/data/objecttypes.json#L49)? For the latter only `publication` and `dataset` are used currently...

**Comment by slint** [comment]
@lnielsen Does [this logic](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/openaire/helpers.py#L36-L61) change because of the new types? From [OpenAIRE's search categories](https://www.openaire.eu/search/find), they place under "Research Data" types like "Software", "Audiovisual", "Film", "Sound", etc.

Relevant cases:

- [OpenAIRE Original ID](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/openaire/helpers.py#L101-L104)
- [OpenAIRE Link](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/openaire/helpers.py#L114-L123)
