### ISSUE TITLE
"Cite as" doesn't work for us

### ISSUE THREAD

**Issue by Axel-Naumann** [zenodo/zenodo#1280]
Hi,

We don't want to be cited as Zenodo suggests. Can you either make this configurable, or at least add an option to not display this box?

Thanks for considering!

Axel.

**Comment by krzysztof** [comment]
@Axel-Naumann we are planning to introduce some configurability to citation styles, but the details on that are still undecided: https://github.com/zenodo/zenodo/issues/874

We might want to keep the box visible, since most users wouldn't opt-out of rendering this box, but perhaps a "verbatim" solution (you can include a raw citation text) would work in cases like yours.
