### ISSUE TITLE
missing file in API uplod: bug

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#1288]
In our (BLR) API based upload we often see, that the upload is not completed and thus the deposit cannot be published.

An example is this file: https://zenodo.org/record/831094 which produces this error message
![image](https://user-images.githubusercontent.com/4609956/30626946-a9a75a3c-9dcd-11e7-862e-8a3d884a8bb1.png)

Originally we didn't have this problem, but now it occurs more often, and adds to deposits that have been saved, are linked from other deposits but cannot be published.

**Comment by slint** [comment]
This one seems to be because of some related identifiers containing strange unicode whitespace characters that usually appear on PDF files. We can have a fix ready for the next deployment, though you might want to update this related identifiers metadata, since they probably won't produce a valid/renderable link.

Example related identifiers (full record JSON available [here](https://zenodo.org/api/records/831094)):

```json
{
    "identifier": "Duperre\u2009N.\u20092015b.\u2009Description\u2009of\u2009the\u2009Frst\u2009visually\u2009cryptic\u2009species\u2009of\u2009Paratropis\u2009(Araneae:\u2009Paratropididae)\u2009fromEcuador.JournalofArachnology4:327-330.http://dx.doi.org/10.1636/arac-43-03-327-330", 
    "relation": "cites", 
    "scheme": "handle"
}, 
{
    "identifier": "Duperre\u2009N.\u2009&\u2009Tapia\u2009E.\u20092015.\u2009Discovery\u2009of\u2009the\u2009Frst\u2009telemid\u2009spider\u2009(Araneae,\u2009Telemidae)\u2009from\u2009South\u2009America,\u2009and\u2009the\u2009Frst\u2009member\u2009of\u2009the\u2009family\u2009bearing\u2009a\u2009stridulatory\u2009organ.\u2009Zootaxa4020(1):191-196.http://dx.doi.org/10.11646/zootaxa.4020.1.9", 
    "relation": "cites", 
    "scheme": "handle"
},
```

**Comment by myrmoteras** [comment]
I replaced the respective related identifier and it works.
