### ISSUE TITLE
openaire: foreign DOIs in export formats

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1327]
Records which have a foreign DOI (i.e. non-Zenodo DOI) needs to have the export format updated.

The DOI should be moved from <identifier> to relatedIdentifier (type=isIdenticalTo) and use Zenodo URL in identifier.

https://issue.openaire.research-infrastructures.eu/issues/629

**Comment by slint** [comment]
I assume this is for the `datacite` and `oai_dc` export formats, which is what OpenAIRE is harvesting automatically. Though since we are now directly indexing records, using the OpenAIRE JSON format, there is no field for related identifiers (there is a [`pids`](https://github.com/zenodo/zenodo/blob/48b97e6916daa0d39513669bef70d5cb1389e04a/zenodo/modules/openaire/schema.py#L66) field though). Also for `identifier` there is [`original_id`](https://github.com/zenodo/zenodo/blob/48b97e6916daa0d39513669bef70d5cb1389e04a/zenodo/modules/openaire/schema.py#L45), which is the `oai` id (`oai:zenodo.org:164231`) for publications or DOI for datasets.
