### ISSUE TITLE
Invalid https certificate

### ISSUE THREAD

**Issue by bitsgalore** [zenodo/zenodo#1358]
Some of the Zenodo subdomains use an invalid (or probably badly configured) https certificate. Two examples:

<https://help.zenodo.org/features/>

and:

<https://about.zenodo.org/>

The "Advanced" error message I'm getting in Firefox is this:

> about.zenodo.org uses an invalid security certificate. The certificate is only valid for the following names: www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com Error code: SSL_ERROR_BAD_CERT_DOMAIN

This issue has been around for at least two days now; might be related to [this announcement](https://twitter.com/ZENODO_ORG/status/931515920018821121) on the Zenodo Twitter account (which was the day before I first came across this).

**Comment by slint** [comment]
The issue has been fixed. The cause was the newly deployed Security Headers, which disallowed HTTPS connections for zenodo.org subdomains (ie. about.zenodo.org, developers.zenodo.org, etc). Subdomains should be accessible after accessing zenodo.org first.

We are working towards introducing HTTPS to the subdomains in order to completely deprecate any plain HTTP pages.
