### ISSUE TITLE
openaire: OAI-PMH missing records in the openaire set

### ISSUE THREAD

**Issue by alessiabardi** [zenodo/zenodo#1397]
I have noticed that some records you have added into OpenAIRE via the direct indexing API are not avaialable from your OAI-PMH endpoint. As a result, records in OpenAIRE are still in a "preview status".
The affected records are the following:
- DOI doi:10.1016/j.epsr.2016.03.012, publication title: "Metalearning to support competitive electricity market players' strategic bidding"
- DOI 10.1016/j.energy.2016.05.127, publication title: MASCEM: Optimizing the performance of a multi-agent system
- DOI 10.1016/j.energy.2016.06.011, publication title: Scenario generation for electric vehicles' uncertain behavior in a smart city environment
- DOI doi:10.1016/j.epsr.2016.10.056, publication title: A stochastic model for energy resources management considering demand response in smart grids
- DOI 10.1016/j.energy.2016.12.108, publication title: Dynamic electricity pricing for electric vehicles using stochastic programming
- DOI doi:10.1016/j.enbuild.2017.03.020, publication title: Demand response implementation in smart households
-  DOI doi:10.1016/j.energy.2016.09.096
publication title: Generation of Realistic Scenarios for Multi-Agent Simulation of Electricity Markets

Can those records be added to the OpenAIRE OAI set or was their insertion wrong in the first place?

**Comment by lnielsen** [comment]
To investigate if and why they records are not in the set.

**Comment by ChiaraBi** [comment]
We found that only 2 of the aforementioned records are not available via the OAI-PMH endpoint:
- DOI: [10.1016/j.epsr.2016.10.056](https://zenodo.org/record/1067134), title: A stochastic model for energy resources management considering demand response in smart grids 
- DOI: [10.1016/j.energy.2016.09.096](https://zenodo.org/record/1067662), title: Generation of Realistic Scenarios for Multi-Agent Simulation of Electricity Markets 

These records have Embargoed Access and both of them have not been accepted by the European Commission Funded Research community yet. In order to have them available at the OAI-PMH endpoint, you should either wait for the embargo date or accept them in the European Commission Funded Research community.
