### ISSUE TITLE
github: records are created for Pre-Releases

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#1413]
As reported by the user, the record is already published for a Pre-Release, which I'm not sure is expected. Needs investigation and maybe changing the webhook/receiver to discard pre-release payloads.

**Comment by uellue** [comment]
Hi, it would be great to not publish every release by default. For our project https://github.com/LiberTEM/LiberTEM we create continuous integration releases and of course pre-releases for testing. We'd like to only publish "real" releases. Ignoring pre-releases could work. As an alternative, it would be great if we could trigger a publication of an existing release manually through the zenodo.org website. Right now, the feedback I got from zenodo.org support was that this only works through the API. That is workable, but a selection list and push button would be more convenient since we already added a .zenodo.json file and generally would like to test the process with selected release candidates. :-)

**Comment by Glignos** [comment]
This is solved now by:https://github.com/inveniosoftware/invenio-github/commit/563afe09eaaa0ebd2b5ab93d3a2d44600c14e6fd

**Comment by ppanero** [comment]
This issue is happening again. See: https://sandbox.zenodo.org/record/958576 coming from two pre-releases in https://github.com/ppanero/zenodo-release-test/releases.

**Comment by ppanero** [comment]
IRL: agreed that all pre-releases go in

**Comment by ZhiyuanChen** [comment]
It seems my prereleases are indexed by zenodo. 
see https://zenodo.org/records/12655182

**Comment by sorenwacker** [comment]
I have the same problem. I don't want pre-releases to be indexed.
