### ISSUE TITLE
stop using md5 hash

### ISSUE THREAD

**Issue by nico202** [zenodo/zenodo#1422]
Hi, on zenodo, to "verify file integrity", the MD5 hash is provided.

It's usually suggested to use something else ([example](https://security.stackexchange.com/questions/33108/why-does-some-popular-software-still-use-md5)).

Becuase of NSA involvements I don't trust SHA (that might have backdoors in it, [explanation](https://arstechnica.com/information-technology/2014/01/how-the-nsa-may-have-put-a-backdoor-in-rsas-cryptography-a-technical-primer/)), but at least there are no known collisions (like there are for [md5](https://www.mathstat.dal.ca/~selinger/md5collision/))

**Comment by krzysztof** [comment]
We're not using MD5 for anything regarding authentication or security. We use MD5 as a "fingerprint", to verify whether the file we have received hasn't been corrupted during upload. For that purpose MD5 is fine, since we're interested in the quick checksum, not in cryptographically-secure hashing.

It's true that MD5 can have issues with collisions, but I'm not sure what an attack vector would be in this case - user manufacturing two files with the same MD5 checksum? I don't think this can be used maliciously in any way, while the probability that a random file upload corruption will produce two identical MD5 hashes is still very low.

**Comment by nico202** [comment]
MD5 is not necessarily faster than SHA1
https://omnifarious.livejournal.com/363945.html
On my tests with linux cli md5/sha1 and with julia MD5.jl/SHA1.jl, md5 is less than 5% faster, but at least we stop using and "spreading" a broken algorithm (a naive user might think that using md5 is ok because you are using it, too).

**Comment by lnielsen** [comment]
MD5 is still widely used for fingerprinting files and completely fine for these use cases. Changing from MD5 to SHA1 (or any other algorithms) requires re-checksumming of 1.2 million files and would possibly break existing API integrations relying on getting MD5 backs. Thus, it's not a simple change of a text string from ``md5`` to ``sha1`` but a rather costly (man-power + CPU) update without no real benefits.

**Comment by nico202** [comment]
Ok thanks
