### ISSUE TITLE
how to request "raw" record export

### ISSUE THREAD

**Issue by yarikoptic** [zenodo/zenodo#1426]
Sorry for a possibly naive question but I have failed to google up the answer:  how to get just the record without it being embedded into an html page, e.g. for https://zenodo.org/record/572345/export/schemaorg_jsonld I expect to simply fetch the .json file without a need to extract it from an html document

**Comment by lnielsen** [comment]
```console
$ curl -H "Accept: application/ld+json" https://zenodo.org/api/records/572345
```

Other formats include:

```
application/json
application/ld+json
application/marcxml+xml
application/vnd.citationstyles.csl+json
application/vnd.zenodo.v1+json
application/x-bibtex
application/x-datacite+xml 
application/x-dc+xml
text/x-bibliography
```

```console
$ curl -H "Accept: text/x-bibliography" "https://zenodo.org/api/records/572345?style=apa&lang=en"
Maier-Hein, Klaus, Neher, Peter, Houde, Jean-Christophe, Caruyer, Emmanuel, Daducci, Alessandro, Dyrby, Tim, … Descoteaux, Maxime. (2015). Tractography Challenge ISMRM 2015 Data [Data set]. Zenodo. http://doi.org/10.5281/zenodo.572345
```

**Comment by yarikoptic** [comment]
Thank you

**Comment by pdurbin** [comment]
Hi! /me waves at @yarikoptic 

I'm here because I googled for "zenodo curl json-ld" and found the answer here. Thank you! From the Zenodo UI, if there's a link to click to get just the JSON I couldn't find it. For more context, please see https://github.com/whole-tale/whole-tale/issues/35#issuecomment-427411937
