### ISSUE TITLE
Add new Metadata

### ISSUE THREAD

**Issue by carobro** [zenodo/zenodo#1679]
Hi all,
We are a student group trying to enhance the zenodo software for similarity calculation.
We want to know where (which file) the metadata is created in zenodo, because we want to add new metadata attributes. Does anybody has an idea, where we can find them ?

**Comment by slint** [comment]
Generally, when we add new metadata fields, we try to do it based on common standards and specific use-cases (e.g. we added a `version` field since it's commonly used for datasets/software).

Before jumping into the code, I would suggest you to drop us a message at https://zenodo.org/support so that we can have a more in-depth discussion on the matter.
