### ISSUE TITLE
Problem running Zenodo following steps in documentation

### ISSUE THREAD

**Issue by karelTole** [zenodo/zenodo#1718]
I was executing the steps of the installation, but at the moment of executing:
$ docker-compose run --rm web bash /code/zenodo/scripts/init.sh

 I get the following error: 
"ERROR: No such service: web"

Thanks for any help!

**Comment by frankois** [comment]
Thanks for reporting this issue.

This is happening because the docker installation process has been modified but the documentation has not been updated yet (this is in progress). Indeed, the web service has been moved from the ``docker-compose.yml`` file to the ``docker-compose.full.yml``

To solve the issue you are having, please execute the following commands instead of the documentation ones:

```bash
cd ~/src/
git clone https://github.com/zenodo/zenodo.git
cd ~/src/zenodo
git checkout master
docker-compose -f docker-compose.full.yml build
docker-compose -f docker-compose.full.yml up -d
```

Then you will be able to run the init script :

```bash
docker-compose -f docker-compose.full.yml run --rm web bash /code/zenodo/scripts/init.sh
```

Please note that the following command is not required anymore as it was included in the init script:
```bash
docker-compose run --rm web bash /code/zenodo/scripts/index.sh
```

**Comment by karelTole** [comment]
Great! I can run zenodo without any inconvenience.
Thanks for your help! :)
