### ISSUE TITLE
New releases for scikit-optimize failed with Unknown error occured

### ISSUE THREAD

**Issue by holgern** [zenodo/zenodo#1948]
All releases since version 0.5.2 have failed with Unkown error occured. I was not able to fix it and it is not clear what the source of the error is. 
Package https://github.com/scikit-optimize/scikit-optimize 
zenodo link:
https://zenodo.org/record/1207017#.XlKPqL1KhPY

**Comment by Glignos** [comment]
So, the error is caused due to a `Bad Credentials` response from GitHub.

I suspect that this is due to the big gap after the last published release on Zenodo (v0.5.2) and the v0.6 ~1 year. So due to inactivity, GitHub expired this token. 
We have now taken precautions to stop this from happening but we cannot refresh already expired tokens. 

The solution, in this case, would be to [navigate here](https://zenodo.org/account/settings/linkedaccounts/) then logout from GitHub and login again. This will provide a fresh token and then you can send a request in our [Support](https://zenodo.org/support) requesting to have your failed releases published.
