### ISSUE TITLE
Uploading a file without an HTTP Content-Length header fails with HTTP 400

### ISSUE THREAD

**Issue by dspinellis** [zenodo/zenodo#1986]
Uploading a file without specifying its length in the HTTP header with a `Content-Length` header element fails with an HTTP 400 `File is smaller than expected` error. The ability to signal the end of a chunked upload via a terminating chunk rather than by specifying its length in the header is required when uploading streamed data, e.g. obtained through input redirection. 

This behavior can be replicated with a line such as the following:
```
echo hi | 
curl -v  --upload-file - 'https://zenodo.org/api/files/YOUR_BUCKET_CODE_HERE/greeting.txt?access_token=YOUR_ACCESS_TOKEN_HERE'
```

Here are the relevant parts of the output.
```
> PUT /api/files/[...]/README.md?access_token=[...] HTTP/1.1
> Host: zenodo.org
> User-Agent: curl/7.64.0
> Accept: */*
> Transfer-Encoding: chunked
> Expect: 100-continue
>
* Expire in 1000 ms for 0 (transfer 0x557e89531e80)
< HTTP/1.1 100 Continue
* Signaling end of chunked upload via terminating chunk.
< HTTP/1.1 400 BAD REQUEST
< Server: nginx/1.16.1
< Date: Tue, 12 May 2020 15:29:29 GMT
< Content-Type: application/json
< Content-Length: 60
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Content-Type, ETag, Link, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset
< X-RateLimit-Limit: 100
< X-RateLimit-Remaining: 97
< X-RateLimit-Reset: 1589297429
< Retry-After: 59
< X-Frame-Options: sameorigin
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Strict-Transport-Security: max-age=0
< Referrer-Policy: strict-origin-when-cross-origin
< X-User-ID: 57930
<
* Connection #0 to host zenodo.org left intact
{"status": 400, "message": "File is smaller than expected."}
```

**Comment by lnielsen** [comment]
It's a requirement that you specify upfront the content length of what you are sending because the storage cluster needs to send the file to a disk server with enough capacity. For smaller files this is not a big issue, but for a 200GB file, this becomes an issue when average disk sizes are around 6TB and disk utilization is high. 

Also, it allows upfront to check file size against available quota. 

We understand that this means you cannot stream unknown size data up into Zenodo. The solution is that you implement a buffer layer in-between Zenodo and your data stream. This also ensure reliability on your end and that no data is lost should there be a connection issue with Zenodo during upload.
