### ISSUE TITLE
Update procedure to update the list of projects from OpenAIRE

### ISSUE THREAD

**Issue by alessiabardi** [zenodo/zenodo#2071]
OpenAIRE has published a json version of the dump at https://doi.org/10.5281/zenodo.4201546 (file named project.tar).
The json dump should be now used in place of the old XML dump that we used to produce.

Each entry of the json file complies with the schema available at https://doi.org/10.5281/zenodo.4238939 (file named project_schema.json).
You should find all fields that you used to find in the XML dump, but in a format that is easier to process (and hopefully to ingest in your local system).

**Comment by slint** [comment]
The new dataset format has some small differences in the available information, although this is not a blocker for the import process.

### Example project from the `projects.tar` dataset

```python
{'callidentifier': 'Tutkijanvaihto Suomeen KY',
 'code': '79046',
 'enddate': '2001-12-31',
 'funding': [{'jurisdiction': 'FI',
   'name': 'Academy of Finland',
   'shortName': 'AKA'}],
 'granted': {'currency': 'EUR', 'fundedamount': 239.0, 'totalcost': 0.0},
 'h2020programme': [],
 'id': '40|aka_________::0041dba1045bb62b634d7bcc1a8f6d3f',
 'openaccessmandatefordataset': False,
 'openaccessmandateforpublications': False,
 'startdate': '2001-08-30',
 'subject': [],
 'title': 'Crime prevention programme'}
```

#### Same grant as it currently is in Zenodo

https://zenodo.org/api/grants/10.13039/501100002341::79046

```json
{
  "created": "2019-12-11T17:18:12.780779+00:00",
  "id": "10.13039/501100002341::79046",
  "links": {
    "self": "https://zenodo.org/api/grants/10.13039/501100002341::79046"
  },
  "metadata": {
    "$schema": "http://zenodo.org/schemas/grants/grant-v1.0.0.json",
    "acronym": "",
    "code": "79046",
    "enddate": "",
    "funder": {
      "$ref": "http://dx.doi.org/10.13039/501100002341"
    },
    "identifiers": {
      "eurepo": "info:eu-repo/grantAgreement/AKA//79046/",
      "oaf": "aka_________::0041dba1045bb62b634d7bcc1a8f6d3f",
      "purl": null
    },
    "internal_id": "10.13039/501100002341::79046",
    "program": "",
    "remote_modified": "2019-04-16",
    "startdate": "",
    "title": "Crime prevention programme",
    "url": ""
  },
  "updated": "2019-12-11T17:18:12.780785+00:00"
}
```

**Comment by alessiabardi** [comment]
Hi @slint , is there a way I can help pushing this task onward?

**Comment by harry-di** [comment]
Dear @slint,
Is there any progress on this task? Some of OpenAIRE's funders, like ANR, have been complaining since December that they cannot link their publications to their projects and Natalia says that this is not looking good for us.
Please let us know how complex this is, and if there is a way we can assist. Many thanks!
All the best,
Harry

**Comment by slint** [comment]
The newest dump has been imported into both Sandbox and Production systems. There are a couple of issues (explained below), but in any case, what was possible to import from the dump has been imported, which is [~50k new projects](https://zenodo.org/api/grants/?q=remote_modified:%5B2020-11-19%20TO%20*%5D).

From the latest `project.tar`, I cannot find any projects by ANR (i.e. `funding.shortName = 'ANR'` or `id = "40|anr_________*"`), which is strange since they do appear e.g. in the EXPLORE portal and the REST API: http://api.openaire.eu/search/projects?funder=ANR&format=json (I see 22,738 total results at the moment).

Overall I see a discrepancy between the totals of the `project.tar` (2,812,592) and what the REST API returns (2,849,154). The difference is 36,562, and even after removing the ANR projects (22,738), we're left with 13,824 projects which are not in the dump. It could be that these are completely new though and not in the latest Nov 2020 dump.

I had a look at maybe trying to harvest the ANR projects from the REST API (via [these parameters](http://api.openaire.eu/search/projects?format=json&funder=ANR)), but from what I understand there's a hard limit on 10k results, which is of course reasonable.

I really hope I'm missing something obvious from the dump regarding the ANR projects, but otherwise, I don't see a way to get them in Zenodo.

**Comment by harry-di** [comment]
Thank you, Alex for the update.
Miriam is checking things on our end, e.g. regarding ANR projects...
We'll get back to you, as soon as we find something.

**Comment by alessiabardi** [comment]
I confirm it is correct. The dump was done on November 2020: we had not ANR projects by that time.
We continuously collect projects from several funders (H2020, Academy of Finland, FWF, RCUK): this is why you see additional 13K missing from the dump.
According to the plan, we will produce another dump this month and you'll get also the ANR projects. 
The important thing is that the process is now in place.

**Comment by harry-di** [comment]
Dear Alex (@slint),
OpenAIRE has now published a new version of the dump at https://doi.org/10.5281/zenodo.3516917 (file named project.tar), which includes the ANR projects.

**Comment by slint** [comment]
@alessiabardi @harry-di all projects have been imported now, and are displayed in the funder selection dropdown in the deposit form:

![image](https://user-images.githubusercontent.com/1814661/119008499-84d75380-b992-11eb-84c3-145bb31f36de.png)

I'm closing this issue since the procedure is in place and we can comfortably import newly added projects from the dump. There are two separate issues still pending regarding the DFG funder projects (https://github.com/zenodo/zenodo/issues/2142) and TARA funder projects (https://github.com/zenodo/zenodo/issues/2171).
