### ISSUE TITLE
broken thumbnails because of "internal server error"

### ISSUE THREAD

**Issue by punkish** [zenodo/zenodo#2097]
for example, see https://zenodo.org/record/3943523/thumb250

# Internal server error
 Error identifier: cbbe961fa6de4358ad4d4b0335b1da39

**Comment by slint** [comment]
Seems to be because the file selected for the thumbnail generation is an `.svg` and the image processing library we're using doesn't do SVG resizing. I see two gradual solutions:

- [ ] Exclude .svg files from thumbnail generation
- [ ] Modify the thumbnail logic for .svg files, to do some XML transformation for resizing, as mentioned in [this SO post](https://stackoverflow.com/a/45177552/2099726).

**Comment by punkish** [comment]
ok, since I am querying for the thumbnail directly, I can't (easily) determine the type of the source file in advance. Excluding the .svg files from thumbnail generation won't solve my problem because I will still look for a thumbnail and will get a broken image (or a 404). The XML transformation logic sounds too kludgy. There are two solutions that I see as being better, one immediate and the other a more solid replacement:

1. If the source file is an SVG, please provide a detectable message instead of an internal server error. That way I can detect whether or not a thumbnail exists and replace a "no preview available" message or a suitable placeholder image.

2. We (Plazi) generate a JPEG or PNG version of the SVG of some suitable size, say 1200px wide (max) that can be used as a viewable version of the original SVG. Then the thumbnail generation can go on as normal.

I cc this to @myrmoteras and @gsautter for their input.

**Comment by gsautter** [comment]
@punkish pretty much from the start, we have been rendering vector graphics as 300 DPI PNGs, and depositing the latter as the primary deposition files, exactly because there is no SVG preview (for security reasons). Those PNGs are always named `figure.png`, and you can synthesize the URL accessing them as `https://zenodo.org/record/<depositionNumber>/files/figure.png`, and via `https://zenodo.org/record/<depositionNumber>/files/figure.png?size=thumbnail` you even readily get a thumbnail.

**Comment by punkish** [comment]
thanks @gsautter this is good to know. I am not really accessing the file or its thumbnail directly. The thumbnails are created by Zenodo and cached. Now that we know that every SVG has a PNG version, perhaps Zenodo's thumbnail generation routine can be modified to use that version as the source (in case the original is an SVG).

By the way, following your instructions above, adding `size=thumbnail` to the querystring for dep no 3943523 does nothing. It returns the same image as without that querystring. See

https://zenodo.org/record/3943523/files/figure.png vs 
https://zenodo.org/record/3943523/files/figure.png?size=thumbnail

**Comment by gsautter** [comment]
Not sure about the `?size=thumbnail` part, it's simply the way @slint told me it should work ... if it has to be done differently, I would like to know just as much.

@punkish the URL with `figure.png` always exists and gets you to a PNG representation (there might be a few legacy exceptions from this rule, but I'm describing how it generally works).

**Comment by punkish** [comment]
> Not sure about the `?size=thumbnail` part, it's simply the way @slint told me it should work ... if it has to be done differently, I would like to know just as much.

@gsautter, the official way is as indicated in my original post above

https://zenodo.org/record/<depositionNumber>/thumb<size>

the officially supported sizes are 10, 50, 100, 250, 750 and 1200. These sizes are generated and cached on Zenodo so querying for them is very efficient.

@slint, from Guido's note, it seems that a PNG representation exists for every SVG. Perhaps you have to modify your thumbnail generation routine so it detects if the source image is SVG, and if so, it uses the PNG version to generate and cache the thumbnails.

Many thanks everyone.

cc @myrmoteras
