### ISSUE TITLE
unexpected response warning

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#2120]
what does this response mean?
https://zenodo.org/record/4555463#.YDQclehKj8A

![image](https://user-images.githubusercontent.com/4609956/108770180-4b8d7400-755a-11eb-9fa2-215f5fa5a02e.png)

when I opened it in another window, the message did not appear again
![image](https://user-images.githubusercontent.com/4609956/108770485-a1fab280-755a-11eb-840e-46bf8a34c343.png)

**Comment by sunarch** [comment]
I don't think this is part of the system, it may have been a momentary network issue. If it hasn't happened since, I suggest closing the issue and reopening it if this happens again in a consistent or reproducible way.

**Comment by myrmoteras** [comment]
sometimes this happens. Just reload the page or wait. You can also get the article by using the DOI link on the right side.

**Comment by sunarch** [comment]
If it happens repeatedly try to describe the circumstances and your browser / program context so that the developers can try to discover the reason when they get to it.

Based on a quick search just now, it seems that other people who encountered a similar error had an "internet download manager" or "Xtreme Download Manager" Chrome add-on, and the problem disappeared when they disabled that add-on.

Do you use something similar on your system?
