### ISSUE TITLE
Can't upload via the API

### ISSUE THREAD

**Issue by arfon** [zenodo/zenodo#213]
Over the last day or so, [this method](https://github.com/openjournals/brief-ideas/blob/master/lib/zenodo_worker.rb#L46-L59) has stopped working on the Journal of Brief Ideas. The [create deposit](https://github.com/openjournals/brief-ideas/blob/master/lib/zenodo_worker.rb#L17-L28) method is still working fine (as in, I am returned a Zenodo ID) but the file upload via the API is returning a 500 error.

I'm trying to process this record but cannot get past the file upload step:
http://beta.briefideas.org/ideas/573b1730eaa5e298e92b98deb1e9b3cc

**Comment by lnielsen** [comment]
Sorry for the lack of communication - was on the go with bad internet. Cause was a number of pretty large uploads (due to having no upper size limits on uploads). We fixed it a couple of times, but problem continued. We have now been in contact with user (who is not to blame), and we will via #34 fix the problem for good with our new storage backend.

**Comment by arfon** [comment]
Awesome. Thanks for the extra information. I just wanted to let you know that we'd be having some issues :+1:
