### ISSUE TITLE
Citation formatting not running

### ISSUE THREAD

**Issue by ctrl-alt-soneca** [zenodo/zenodo#2163]
The default citation format cannot process the following CSL JSON:

```
{
  "publisher": "Zenodo", 
  "DOI": "10.5281/zenodo.4699614", 
  "container_title": "BRAMS", 
  "language": "eng", 
  "title": "Britain and the EU", 
  "issued": {
    "date-parts": [
      [
        2021, 
        4, 
        18
      ]
    ]
  }, 
  "abstract": "<p>The author discusses arguments for and against the UK&#39;s membership in the EU and summarises the benefits for the country that can follow Brexit if it is wisely proceeded.</p>", 
  "ISSN": "2667-9299", 
  "page": "18-38, 123-127", 
  "volume": "1", 
  "version": "MAJOR", 
  "author": [
    {
      "family": "Jeremy J. Ramsden"
    }
  ], 
  "type": "article-journal", 
  "issue": "1", 
  "id": "4699614"
}
```

**Comment by slint** [comment]
Apparently, the issue seems to be related with the `page` value. The underlying `citeproc-py` library splits the string on dash (`-`), and since there are 2 ranges specified this fails.

Apparently, there are many fixes (even specific to [handling the `page` field](https://github.com/brechtm/citeproc-py/commit/a68040dc2d1f1e7275f7f13874cb69c5579e37e8)) and changes introduced to the library, so it might be that upgrading to a newer version could fix things.
