### ISSUE TITLE
thumbnail URI leads to 404

### ISSUE THREAD

**Issue by punkish** [zenodo/zenodo#2308]
https://zenodo.org/api/records/6352821

```
"thumbs": {
      "10": "https://zenodo.org/record/6352821/thumb10",
      "50": "https://zenodo.org/record/6352821/thumb50",
      "100": "https://zenodo.org/record/6352821/thumb100",
      "250": "https://zenodo.org/record/6352821/thumb250",
      "750": "https://zenodo.org/record/6352821/thumb750",
      "1200": "https://zenodo.org/record/6352821/thumb1200"
    }
```

**update:** to be clear, the actual 250px thumbnail actually is being generated *if* reached by the actual URL (https://zenodo.org/api/iiif/v2/894b372a-be5b-41c0-b443-110b93a68b25:e9c05370-06bd-49cc-a3fb-486e317ef42c:oo_511441.jpeg/full/250,/0/default.jpg). It is the *thumbs* aliases that are not resolving properly

adding @gsautter and @myrmoteras to this, just in case it is an issue on TB side

**Comment by gsautter** [comment]
Well, the figure proper is there, see https://zenodo.org/record/6352821 ... the thumbnails are generated on the Zenodo side.

**Comment by punkish** [comment]
> Well, the figure proper is there, see https://zenodo.org/record/6352821 ... the thumbnails are generated on the Zenodo side.

yes, you are correct. Hence the "just in case" in my original post 😄

**Comment by slint** [comment]
Suspicion confirmed, there's `.jpeg` missing from a list of valid "extensions":  https://github.com/zenodo/zenodo/blob/f091af8f2d0bfac2fdaf53222160f8e037d5a0e6/zenodo/modules/records/views.py#L466

The fix is to import and use the following list [from `invenio-iiif`](https://github.com/inveniosoftware/invenio-iiif/blob/23842e852c02cbfd103b9b296db5f450b971c0d9/invenio_iiif/previewer.py#L19).
