### ISSUE TITLE
github: doi badge link wrong

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#276]
DOI badge on https://zenodo.org/account/settings/github/ is not properly advertised, but more importantly the URL link does to the current DOI which will not be the latest DOI. It should instead go to intermediary URL which will redirect to the latest version.

**Comment by cpaulik** [comment]
Thanks for the prompt reply (via email). I personally had no issue finding the functionality or the badge. 

But I am not sure if always linking to the latest DOI is the solution since this would mean that also old versions of the software link to the latest DOI which is probably not what is wanted if citation of the correct version is desired?

**Comment by hugovk** [comment]
For citing a release, you'll generally want to link to the actual release.

But for putting a badge on a repo, I guess the most common use case (and what I was expecting), is the badge links to the latest release (or a summary of releases). 

This is how badges generally work on repos: a Travis CI badge links to a summary page showing the latest build, and not to the release when the badge was added; a Coveralls badge links to a summary page of recent builds, and not that for when the badge was added; and so on.

And it's good the issuing of DOIs for new releases due to webhooks, but a bit annoying if we need to update the README files with new badges for every release.

So, if you want to keep existing badges linking to actual releases, how about creating a new badge that can be used to link to the latest release (or a summary)?

**Comment by cpaulik** [comment]
I'm all for keeping the convenience of getting a DOI through a webhook. 

I think it would be great if the badge would link not to the latest DOI but to a website listing all the DOI's and versions issued for the git repository. In this way it is easy to choose the correct DOI for the version actually used.

**Comment by lnielsen** [comment]
> This is how badges generally work on repos: a Travis CI badge links to a summary page showing the latest build, and not to the release when the badge was added; a Coveralls badge links to a summary page of recent builds, and not that for when the badge was added; and so on.

@hugovk @cpaulik: It's a good idea that we could create an intermediary page showing all the releases. We can likely do this prior to landing versioning support (see #34) which will allow you to browse the history of releases.

> And it's good the issuing of DOIs for new releases due to webhooks, but a bit annoying if we need to update the README files with new badges for every release.

I fully agree, you definitely should not have to do that.

**Comment by Juanlu001** [comment]
Perhaps this is not the appropriate place to ask, but I usually find myself in the following dilemma: *how do I ship the DOI of a release with that release*? Imagine: first I write the README, then I release, and next I assign the DOI in Zenodo, therefore cannot include it in the just released package. What I did last time was to upload a release candidate first. I think having some kind of "dynamic link" or "link to latest DOI" thing would be very useful.

**Comment by hugovk** [comment]
@bouzlibop In addition to badges linking to individual releases,  is it now possible to link badges to some sort of summary page? How?

**Comment by lnielsen** [comment]
Changes have been deployed in production now.

We do not have a summary page yet. This will be implemented along with versioning support.

**Comment by wmayner** [comment]
> How do I ship the DOI of a release with that release?

@Juanlu001, I've been having that exact problem. Seems like it's been fixed, but I can't seem to see how to get around this (sorry if it's obvious).

**Comment by Juanlu001** [comment]
@wmayner, I've come to the conclusion that it simply doesn't make sense. Think of it as a checksum of your repository: you cannot include it inside, since it would make the checksum change, etc. In the end I included the "latest DOI" link in the README, and put the actual DOI in the GitHub release notes (since it's fine to edit the descriptions), see https://github.com/poliastro/poliastro/releases/tag/v0.4.0

**Comment by wmayner** [comment]
@Juanlu001, yes, it's certainly impossible if the DOI is a function of the repository state, like a checksum. However, I don't think that's the case. I'm not sure how DOIs are assigned, but this should be possible in principle.

One obvious idea is to have a “next release” DOI that is already reserved for the next version when you release the current version. That way you know the DOI in advance and could put it in the README, etc.

Yesterday I checked out your project and followed your example with the latest DOI link. Didn't notice the DOI in the releases—that's a good idea, I'll do that too.

**Comment by wmayner** [comment]
@bouzlibop, do you think the above idea for a “next release” DOI is feasible or desirable?

**Comment by cpaulik** [comment]
@lnielsen up there https://github.com/zenodo/zenodo/issues/276#issuecomment-123738040 you said
> We do not have a summary page yet. This will be implemented along with versioning support.

Is there a issue where we could track progress on that? In the current Zenodo release I can see a summary in my Github integrations settings but other users have no way of seeing a summary of a specific package and as far as I can tell there is no way to link to a summary page of all the releases of a software.

**Comment by joelnitta** [comment]
For anybody still coming across this: there is now a badge available that always points to the most recent DOI. It is accessed under the "GitHub / Repository" menu in your Zenodo account. By using this badge, there is no need to edit the README with each version bump.

Here are some example screen shots from a recent repo of mine:

<img width="1168" alt="zenodo-1" src="https://user-images.githubusercontent.com/13459362/125597842-fb82c56f-8c8f-494d-acb1-7ca883aaf5ed.png">

<img width="634" alt="zenodo-2" src="https://user-images.githubusercontent.com/13459362/125597921-feefbcb1-439e-4951-9f3e-4b176521e365.png">

**Comment by sorenwacker** [comment]
It is not obvious that you can click on this badge and that this would reveal the desired information.
