### ISSUE TITLE
idea: sorting licenses

### ISSUE THREAD

**Issue by LibrarPotter** [zenodo/zenodo#332]
Could it be worth it to sort the license drop-down menu to only include licenses that would be appropriate for the kind of resource being uploaded (according to the file-type specified by the user)?  E.g. Not giving Creative Commons as an option for Code; Not giving Apache as an option for a publication.

**Comment by lnielsen** [comment]
It's not as clear cut as it might seem and I'm sure if we limit the list of licenses, we'll have people who doesn't fit in. However I do see that we should try to make it easier to select the right license. Perhaps by grouping the licenses or similar.

**Comment by LibrarPotter** [comment]
Grouping by what they are often used for OR giving a sort by "Openness" or similar option

**Comment by krzysztof** [comment]
Pavel Stranak suggested this implementation of JS-based license selection helper

code:
https://github.com/ufal/public-license-selector
and example:
https://ufal.github.io/public-license-selector/

This could probably address the need for "grouping" the licenses, without actual grouping by other context, i.e. the license "helper" form can already narrow-down the set after few clicks, without hard-exclusion of any license.
It seems like the lib above has a fixed set of licenses already, but perhaps it wouldn't be too difficult to extend it from elsewhere, otherwise it would at least be a nice reference.
