### ISSUE TITLE
What does Deposition state of inprogress mean?

### ISSUE THREAD

**Issue by zdennis** [zenodo/zenodo#348]
What does the `inprogress` state means for a Deposition?

I ask because when creating a deposition thru the API it is either immediately in "done" state or it is in the "inprogress" state. When it's in the inprogress state it is not editable, etc, but it's not clear to me why it's inprogress. It also seems to remain in the inprogress state for varying amounts of time. Sometimes a few seconds other times several minutes.

I couldn't find any documentation as to what the states represent just that they exist. If there are docs for this could someone point me in the direction?

Thanks!

**Comment by zdennis** [comment]
After a little more investigation it seems that a Deposition is in `inprogress` from the moment its created to the moment you attach a file and publish the deposition. 

Then it is marked as in progress whenever you `edit` the deposition up until the point that you `publish` it again. 

And a Deposition without a file cannot be `published`.

**Comment by zdennis** [comment]
Another update: it seems that frequently once a Deposition is published you cannot _edit_ it **until it has been integrated**.  You will get an HTTP 409 Conflict error until that happens, e.g.:

> {"status": 409, "message": "Conflict", "errors": "Upload not yet fully integrated. Please wait a few moments."}

This begs the question, what does _integrating_ mean and why does that often take a long time to achieve? The Deposition's state says `done`, but you cannot edit the deposition until it has been integrated.

**Comment by zdennis** [comment]
On a more general process note (not specifically Zenodo) I pushed up some spike code to [issues/339_export_csv_report](https://github.com/articlemetrics/lagotto/compare/issues/339_export_csv_report?expand=1)

Here's what a brain dump of what I'm thinking based on this spike. This is intended to work for what we need today, but to allow allow re-use for other files we may want to export later (either to Zenodo or other services):

**FileExport** is a model that represents any file that we want to export. It has a generic data model that more specialized subclasses would rely/build on. FileExport implements STI so subclasses can have their own specialized logic instantiated automatically.

**ZenodoFileExport** is a subclass of FileExport and implements the responsibility for what it means to upload a file to Zenodo. If we wanted to export multiple kinds of files to Zenodo this would either own that responsibility or we could have multiple _ZenodoXXXFileExport_ classes that are responsible for specific kinds of files. 

If Lagotto ever needs to export data to a new service it'd be as simple as implementing a new FileExport subclass that acted as the integration point.

**rake export:all** would look at all FileExport(s) that have not been exported and that are not in the process of exporting and it will queue up a generic FileExportJob for the specific FileExport.

**FileExportJob** is an ActiveJob will then find the specific FileExport in the DB and then tell it it `export!` itself. If a FileExport successfully finishes it will record the response as well as the  finish time of the export. It also records the start time when the export begins.  

Over time there will be a record of all of the files that are exported along with information that can be used to track down that information for later retrieval if necessary.

**API_KEYs etc** would be added as environment variables in the same way it is done today.

#### Thoughts, Concerns, Feedback?

Let me know. Thanks!

**Comment by bouzlibop** [comment]
@zdennis, first of all I do apologize for a delay with this answer. @lnielsen is currently on holidays and will be back at the end of the next week. As he is the one who has extensive knowledge on this issue - he will provide you with more detailed answer on your question than I will do.

I understand pressure of time and meanwhile I will try to provide you with brief information on this topic.

**1. API docs**

As you pointed out in this issue:
>I couldn't find any documentation as to what the states represent just that they exist. If there are docs for this could someone point me in the direction?

and also the one in https://github.com/sprotocols/zenodo/issues/3

>I'd link to the section on Zenodo's API but there is no way to link to that particular section

Current [api docs page](https://zenodo.org/dev) is not very user friendly (easily searchable, referable etc) we are working on improving it. There is an [issue opened](https://github.com/zenodo/zenodo/issues/340), which first of all will deal with moving this static page to the new module, which will allow to introduce changes more easily and (what's probably more important from the perspective of the question you asked) we will change layout and update the content of that page. Hopefully this will be done in upcoming weeks. Any suggestion of the things that are missing are welcomed.

**2. Deposition states**

> After a little more investigation it seems that a Deposition is in inprogress from the moment its created to the moment you attach a file and publish the deposition.
Then it is marked as in progress whenever you edit the deposition up until the point that you publish it again.
And a Deposition without a file cannot be published.

As far as I know that is exactly how it works.

> The Deposition's state says done, but you cannot edit the deposition until it has been integrated.

I understand this is kind of misleading. This state (`done`, but you cannot edit it) means that you successfully submitted a deposition and it will soon be published - there are some tasks to be done on your deposition that need to finish before your record will be fully integrated...

> This begs the question, what does integrating mean and why does that often take a long time to achieve? 

All submitted uploads go to the queue - specifically some tasks are scheduled in order to be done before record goes published. Usually it should take less than 5min for all of them to be done for a single record, but as our queue gets heavily loaded this time can even jump in a worse case to a few hours. This is the area for improvement for us. And to sum up, during the time there are some tasks connected to the specific deposition in the queue, deposition is in `done` state but cannot be edited.

Additionally, extra knowledge resource of our api might be for you our [api testsuite](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/deposit/testsuite/test_zenodo_api.py).

**Comment by lnielsen** [comment]
Just adding a few extra comments:

> And a Deposition without a file cannot be published.

Yes, we don't support having only metadata records. Since we register DOIs for all uploads, there must be a file associated.

**Integration**: It's as @bouzlibop described. Just to add that the underlying issue is in Invenio (platform Zenodo is based on) and is being fixed right now. By end September/October we should hopefully be past this problem, and changes should be immediate.
