### ISSUE TITLE
Notify users about upcoming maintenance

### ISSUE THREAD

**Issue by Daniel-Mietchen** [zenodo/zenodo#472]
Maintenance can disrupt user workflows, so it would be useful to have some ways to notify users about upcoming maintenance. The mechanism would probably have to be different for users who are logged in versus those who are not.

**Comment by lnielsen** [comment]
Apologies for taking so long to respond to this. What you experienced was unfortunately unplanned downtime (however our default outage message would say the site was undergoing maintenance which is incorrect). We will change the default message so that in case of unplanned maintenance then it will correctly state it so.

Regarding planned upcoming maintenance see https://github.com/zenodo/zenodo/wiki/Planned-intervention
