### ISSUE TITLE
Upload page after manual installation

### ISSUE THREAD

**Issue by kyrginis** [zenodo/zenodo#659]
Hello,

 At GRNET (the Greek NREN) we are looking for a data repository and we are testing zenodo.

After doing a manual installation following https://github.com/zenodo/zenodo/blob/master/docs/installation.rst, the upload page we are getting, has only a metadata form for record type, publication type etc, but no buttons for file uploading like the ones in https://zenodo.org/deposit/. 

We did the manual installation because the Docker installation failed like described in  issue #459.

Could you give us any hints on how to get a working upload page ?

Thanks a lot,
Kyriakos Gkinis
GRNET

**Comment by lnielsen** [comment]
@kyrginis We're in the process of rewriting large parts of Zenodo and the upload part is not done yet. Please also note the license disclaimer at: http://zenodo.readthedocs.io/license.html

```
Zenodo source code is licensed under GNU General Public License version 2. This does not apply to the name Zenodo (TM) and the Zenodo logo which are trademarked by CERN. Thus if you instantiate the software you must change the branding to your own.
```

I.e. Zenodo is the **service** run at ``zenodo.org`` by CERN, whereas Invenio is the **software** (repository framework) that you usually want to instantiate and run. EUDAT is building a data repository called B2SHARE, built on Invenio and similar to Zenodo, but intended to be a software that you can instantiate. This is important since for Zenodo we may make breaking code changes at any point in time, and do not take any other installations into account than zenodo.org - B2SHARE on the other hand provide releases, and will provide upgrade instructions for each release etc. I.e. if you want a local data repository go with basic Invenio or B2SHARE - if you want a cloud service go with http://zenodo.org. For zenodo.org we'll be happy to receive code contributions as long as it adheres to our quality standards and fit our vision.


Actually, what you'd likely want to use is rather Invenio, which is the underlying repository framework that Zenodo is built on top. EUDAT is building B2SHARE which
