### ISSUE TITLE
orcid: log-in with ORCID does not work for disconnected accounts.

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#921]
1. Log in to Zenodo and connect your ORCID account (or log-in with ORCID in the first place).
2. Go to linked accounts and disconnect from ORCID.
3. Log-out and try to connect with ORCID again - you should be redirected to sign-up page (bug).

**Comment by lnielsen** [comment]
This is expected behaviour.

1. You can't sign up with ORCID in the first place without providing email/username.
2. When user disconnects the account we no longer have any information (like a verified email address) that we can use on the second sign-up attempt to  automatically identify the local account. Hence if the user didn't set a password and want to relink the local account with the orcid account, then the user must first reset their local account password and login, the connect the ORCID.
