### ISSUE TITLE
records: automatic updating of related identifiers

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#925]
Simple example:
1. User creates a new record `456` with a related identifier "is new version of", that points to the old Zenodo record `123`.
2. On publication (or during editing and "Save") of the new record, the `123` record's related identifier's (if the record is owned by the same user) automatically (or after the user's approval) gets updated with a related identifier "is previous version of" that points to record `456`.

There could be of course even more applications of this pattern for other related identifiers "pairs".

**Comment by krzysztof** [comment]
The related identifiers are not in the record's metadata, but are indexed.

At the moment only the "hasPart" "isPartOf" is there, simply because next/previous version is tricky when it comes to semantic-versioned records which end up in Zenodo (i.e. software releases such as: 1.0 -> 2.0 -> 1.1 -> 2.1 -> 1.2 would "incorrectly" refer to next/previous version).

If we do not plan on handling that, this issue can be closed, otherwise we should think how to handle this problem (disable previous/next version on GitHub records only?)

**Comment by lnielsen** [comment]
I think we can close it. We will not do more for now.
