### ISSUE TITLE
docs: oai-pmh docs should not suggest harvesting user-zenodo

### ISSUE THREAD

**Issue by pkraker** [zenodo/zenodo#939]
I am new to OAI-PMH, so I may be doing something wrong here, but I am only able to retrieve 4192 records using the `user-zenodo` set. This is also the number of records that's reported by the resumptionToken when executing https://zenodo.org/oai2d?verb=ListRecords&metadataPrefix=oai_dc&set=user-zenodo

There seem to be no records before September 2016, as this query gives no results: 
https://zenodo.org/oai2d?verb=ListRecords&metadataPrefix=oai_dc&set=user-zenodo&from=2014-01-01&until=2016-08-31

But this one does reports the 4192 records that I got above: https://zenodo.org/oai2d?verb=ListRecords&metadataPrefix=oai_dc&set=user-zenodo&from=2016-09-01&until=2017-01-11

**Comment by lnielsen** [comment]
The set ``user-zenodo`` is what is being displayed in the [community Zenodo](https://zenodo.org/communities/zenodo/search) and is essentially what has been on the Zenodo frontpage. 

If you want all of Zenodo use https://zenodo.org/oai2d?verb=ListRecords&metadataPrefix=oai_dc instead.

The reason why there are only record updates from September 2016, is because we made a major update on Sep 12 where all records essentially were updated due to a large migration.

**Comment by pkraker** [comment]
Thanks for the quick reply and the clarification! You should consider updating your docs with this information, as they still advise to use user-zenodo: https://zenodo.org/dev#harvest-sets

**Comment by lnielsen** [comment]
Thanks for spotting the problem. We'll update the documentation.

**Comment by krzysztof** [comment]
Should be fixed when this goes in: https://github.com/zenodo/zenodo/pull/968
