### ISSUE TITLE
deposit: removing DOI when editing a published record shouldn't be possible

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#942]
Currently editing a published record and completely removing/clearing the DOI field in the deposit form, is a "Save"-able state, from which though the user cannot recover (clicking "Pre-reserve DOI", or filling in the DOI manually and saving results to an "internal server error").

In order to tackle this issue, two steps are required:
- [x] Proper validation of the submitted deposit data with regard to the fact that it's a deposit of an already published record.
- [ ] Disabling the DOI field in deposit form when the published record uses a Zenodo DOI.

**Comment by krzysztof** [comment]
Steps to reproduce this error:

1. Create a new deposit, fill in all metadata + file, and provide an external DOI, e.g.: "10.1000/12345"
2. Click "Save" and "Publish"
3. Edit the record, remove the DOI, click "Save" (Saves the deposit properly)
4. At this point Saving the deposit throws Internal Server Error on Saving/Publishing.

**Comment by kapilkd13** [comment]
Hi @krzysztof  I have reproduced the issue.
I have some questions regarding the step 1 you mentioned "Proper validation of the submitted deposit data with regard to the fact that it's a deposit of an already published record."
should we completely disallow users to genrate DOI if record is already published.
Also can you explain little  bit about Validation that need to be done

**Comment by krzysztof** [comment]
The rules for DOI editing are as follows:

When you first create a deposit, you can either:
a) provide you own DOI which you might already gotten from a publisher
b) opt-in for a Zenodo DOI either by leaving the DOI field empty, or clicking pre-reserve DOI, which is simply showing you what your DOI will be (end result is, that the DOI is 'zenodo' DOI which we generate for the user).

Now, if you click publish for the first time, and if you chose a), you can later edit the DOI field (e.g. you might have made a typo in the DOI field - we wouldn't know that since we didn't register it ourselves). Editing of the DOI in case of a) is possible.

In case of b), it's no longer possible to change the DOI after you're published the record. When you open the deposit for editing the DOI field should be disabled (you can no longer change the DOI).

The DOI validation code is stored in the DOI field schema here: https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/serializers/fields/doi.py

**Comment by krzysztof** [comment]
So in the problem description above at Step 3, it should not be possible to save an "empty" DOI, once the record has been published.

Second issue is that it should not be possible to Save an already published deposit (during editing), when the Zenodo DOI has been already registered.

**Comment by jainaman224** [comment]
@kapilkd13 Are you working on this...?

**Comment by kapilkd13** [comment]
Not right now, Please go for it.:)

**Comment by jainaman224** [comment]
I am currently working on another issue. If anyone else wants to complete go for it.

**Comment by guptavaibhav18197** [comment]
I would like to take up this issue.

**Comment by jainaman224** [comment]
@guptavaibhav18197 Go ahead :+1:.

**Comment by guptavaibhav18197** [comment]
@jainaman224 
I have gone through almost entire code flow, the only thing that I am trying to figure out if where is this_validate function is being called from. Any clues about that?

**Comment by jainaman224** [comment]
@guptavaibhav18197 It would be helpful for me if you can add the link the particular line.

**Comment by guptavaibhav18197** [comment]
@jainaman224 I have updated the comment ^

**Comment by jainaman224** [comment]
This is marshmallow form validation whenever the form is submitted this validator function is invoked.

**Comment by guptavaibhav18197** [comment]
@jainaman224  The thing is whenever the DOI field is empty while updating the form , this  https://github.com/zenodo/zenodo/blob/master/zenodo/modules/deposit/loaders/base.py#L80 function is not being invoked.
That is why I am wondering where is it being called from.

**Comment by jainaman224** [comment]
No idea about this. I need to check the codebase but currently occupied in other important work.

**Comment by krzysztof** [comment]
It was almost fixed here, but requires further attention: https://github.com/zenodo/zenodo/pull/1043

**Comment by Glignos** [comment]
https://github.com/zenodo/zenodo/pull/1715
