### ISSUE TITLE
Zenodo lists only some repositories from organisation

### ISSUE THREAD

**Issue by hertzsprung** [zenodo/zenodo#944]
I have zenodo connected to my github account and I have received permission from the owner of the @AtmosFOAM organisation.  However, I can only see two AtmosFOAM repositories listed in zenodo: `AtmosFOAM/gmd-geodesic-mesh` and `AtmosFOAM/OpenFOAM-dev`.  Is there a reason why the other public repositories don't appear in zenodo?

**Comment by hertzsprung** [comment]
Thinking about it, I assume zenodo's listing only those repositories which I created rather than listing those which I have read/write access.  Is this by design?

**Comment by krzysztof** [comment]
Zenodo is listing those repositories, to which you have "admin" permissions - this is so that Zenodo can install webhooks on those repos. Those include: your personal repositories and organizational repositories to which you have admin access, either as an admin of the whole organization, or as an admin of the specific organizational repositories.

@hertzsprung Perhaps you were given admin access only to those two repositories of AtmosFOAM org?

**Comment by hertzsprung** [comment]
Thanks for the explanation, perhaps this could be added to the info box at the top of the repositories list?  I'll ask the organisation owner if I can get (temporary) admin access for the other repositories.
